### ISSUE TITLE
Multiple @Cacheable executions

### ISSUE THREAD

**Issue by ikovalyov** [micronaut-projects/micronaut-cache#107]
Imagine scenario:

You have a function which performs long computation
You marked it as @Cacheable
You called it several times before first call was resolved
Expected: Only 1 actual call to the function executed, each callee is getting CompetableFuture(Single/etc.) linked to the result of the first call

Actual: Multiple calls to the function registered.

**Comment by ikovalyov** [comment]
https://github.com/micronaut-projects/micronaut-cache/pull/224

**Comment by alvarosanchez** [comment]
Closing this as #224 was closed by its author and original poster of this issue.
