### ISSUE TITLE
Provide a NoOp cache implementation

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-cache#12]
@graemerocher If interested I can provide a PR.

**Comment by graemerocher** [comment]
contributions welcome!

**Comment by alvarosanchez** [comment]
Note that this should be in micronaut-core/runtime, since cache-core was again moved back there.

**Comment by graemerocher** [comment]
Depends it could be in a `cache-noop` subproject

**Comment by marceloverdijk** [comment]
Yes, I was thinking about a `cache-noop` subproject myself as well. I will provide a PR this week.

**Comment by alvarosanchez** [comment]
@marceloverdijk can this be closed?

**Comment by marceloverdijk** [comment]
Closed as per https://github.com/micronaut-projects/micronaut-cache/pull/19
