### ISSUE TITLE
@Cacheable causes ThreadLocal leak in OpenTracing

### ISSUE THREAD

**Issue by David-16** [micronaut-projects/micronaut-cache#135]
This is to reopen https://github.com/micronaut-projects/micronaut-cache/issues/114

Please see my 12 June 2020 comment: https://github.com/micronaut-projects/micronaut-cache/issues/114#issuecomment-643456611

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

See https://github.com/micronaut-projects/micronaut-cache/issues/114

### Expected Behaviour

See https://github.com/micronaut-projects/micronaut-cache/issues/114

### Actual Behaviour

See https://github.com/micronaut-projects/micronaut-cache/issues/114

### Environment Information

- **Micronaut Version:** bom: 2.0.0.M3, cache: 2.0.0.M1

### Example Application

See https://github.com/micronaut-projects/micronaut-cache/issues/114

**Comment by alvarosanchez** [comment]
This does not reproduce with the latest Micronaut Core and Cache.

Here is a patch that can be applied to https://github.com/David-16/micronaut-issues/tree/master/tracing-issue-3:

[micronaut-upgrade.patch.zip](https://github.com/micronaut-projects/micronaut-cache/files/5815524/micronaut-upgrade.patch.zip)
