### ISSUE TITLE
Cache manager implementations should be swappable easily (per env)

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-cache#14]
Currently the `EhcacheManager` simply `@Replaces` the `DefaultCacheManager`: https://github.com/micronaut-projects/micronaut-cache/blob/master/cache-ehcache/src/main/java/io/micronaut/cache/ehcache/EhcacheManager.java#L44

I assume this is *not* the intended behavior?
I would assume that different cache implementations could be used in different environments based on e.g. a property. Now it seems the used cache manager is coupled to cache dependency.

Note the same goes for the `HazelcastManager`.

**Comment by marceloverdijk** [comment]
Yes I understand it is more complex, but honestly I don't think the current solution offers enough flexibility.

**Comment by jameskleeh** [comment]
I suggest the creation of a `CompositeCacheManager` will look for caches in each of the other cache managers. That would allow for multiple beans

**Comment by alvarosanchez** [comment]
That is certainly another option. However, I'm unclear on whether the effort is worth.

**Comment by jameskleeh** [comment]
Resolved this for ehcache and hazelcast changes are coming
