### ISSUE TITLE
Add support for Coherence

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-cache#152]
https://coherence.community/

**Comment by pollend** [comment]
would this live in its own repo similar to ignite.

**Comment by alvarosanchez** [comment]
Possibly. If it's only for sync/async cache implementations, I think it's fine to have it here.

We can always spin it off if needed.

**Comment by graemerocher** [comment]
@aseovic at Oracle is looking into this

**Comment by aseovic** [comment]
Yes, we are looking into this, although I'm waiting for @thegridman to finish some prerequisite work before he can tackle Micronaut integration.

That said, from what I've seen, most of our competitors have a very basic integration that only adds caching support. That's certainly low-hanging fruit and easy to do, but I think it's also the least valuable integration we can do.

We plan to do a lot more, so you can not only use Coherence for caching, but also as a general purpose data store, messaging system, etc. We also want to provide low-level support for dependency injection, configuration, events, metrics, etc. along the lines of what we've done for the Helidon/MicroProfile integration.

We will likely end up with multiple modules for all these things (core, config. metrics, data, caching) and will need to decide whether we should "sprinkle" them across corresponding Micronaut modules (the way Hazelcast does), or if we can group them together under top-level `micronaut-coherence` repo (along the lines of Ignite). My personal preference is the latter, but happy to do the former if there are some benefits to it.

**Comment by alvarosanchez** [comment]
@aseovic awesome! The last time I interacted with Coherence was when it was still Tangosol 😅 . Great to hear that it can do so many things now.

This is a clear example of a module that needs its own repo. When you guys are ready, ping @graemerocher or me, and we will assist you with the new repository.

**Comment by alvarosanchez** [comment]
This is already being worked on at https://github.com/micronaut-projects/micronaut-coherence
