### ISSUE TITLE
Kotlin suspend functions support with caching

### ISSUE THREAD

**Issue by ikovalyov** [micronaut-projects/micronaut-cache#183]
Hi.
Right now kotlin suspend function are not recognized by the CacheInterceptor as async return type. As result if we try to use Cacheable over suspend functions application hangs up.
Is it possible to add support of the suspend functions to the micronaut-cache project?
Thanks.

**Comment by dave08** [comment]
@konrad-kaminski , what would it involve if I would provide a PR for this? Any little tips you can give? Thanks!

**Comment by dstepanov** [comment]
Should be possible after https://github.com/micronaut-projects/micronaut-cache/pull/227 is merged

**Comment by zsiegel** [comment]
@dave08 in the meantime you can use the jdk8 futures compatibility library from Jetbrains to make the caching annotations happy.

```
org.jetbrains.kotlinx:kotlinx-coroutines-jdk8
```

For example you can write a function thats cacheable that interops with Kotlin and coroutines nicely.

```kotlin
@Cacheable("data")
fun getData(symbol: String) = CoroutineScope(Dispatchers.Default).future {
    //Do your work in here
}
```

Then you can use that function in a coroutine somewhere else. Dont forget to `await()` the result
```kotlin
suspend fun anotherFunction() {
    val result = getData("data").await()
}
```

**Comment by jacekgajek** [comment]
Sample project: https://github.com/jacekgajek/redis-error-demo

**Comment by jacekgajek** [comment]
The current problem is not that a controller hangs. Instead, the default generated key is random (it basically has a memory address inside). It can be seen if a custom `CacheKeyGenerator` is hooked up. 
```
class CustomCacheKeyGenerator : CacheKeyGenerator {
    override fun generateKey(annotationMetadata: AnnotationMetadata, vararg params: Any?): Any {
        println(params)
        return params ?: "foo"
    }
}
```
The last parameter of the `vararg params` is some temporary object which changes on every call. Therefore, although maybe some data is stored in a cache, the cache is never read because the key is always different.

**Comment by graemerocher** [comment]
the logic that calls https://github.com/micronaut-projects/micronaut-cache/blob/master/cache-core/src/main/java/io/micronaut/cache/interceptor/CacheKeyGenerator.java#L36 needs to remove the last arg if the method a suspend function

**Comment by jacekgajek** [comment]
Is this OK? https://github.com/micronaut-projects/micronaut-cache/pull/391

**Comment by graemerocher** [comment]
looks good yeah. Thanks

**Comment by jacekgajek** [comment]
PR recreated with CLA signed.
https://github.com/micronaut-projects/micronaut-cache/pull/392

**Comment by kutlueren** [comment]
> ```kotlin
> @Cacheable("data")
> ```

I have tried this but did not work for me. Am I missing something?

```
    override suspend fun getAccessToken(): String {
        try {
            return getData().await()
        } catch (e: Exception) {
            logger.error(e) { "request failed" }

            throw e
        }
    }
    
        @Cacheable
    fun getData(): CompletableFuture<String> = CoroutineScope(Dispatchers.Default).future {
        println("fetching the data")

        return@future "test"
    }
    
```

**Comment by kutlueren** [comment]
> @dave08 in the meantime you can use the jdk8 futures compatibility library from Jetbrains to make the caching annotations happy.
> 
> ```
> org.jetbrains.kotlinx:kotlinx-coroutines-jdk8
> ```
> 
> For example you can write a function thats cacheable that interops with Kotlin and coroutines nicely.
> 
> ```kotlin
> @Cacheable("data")
> fun getData(symbol: String) = CoroutineScope(Dispatchers.Default).future {
>     //Do your work in here
> }
> ```
> 
> Then you can use that function in a coroutine somewhere else. Dont forget to `await()` the result
> 
> ```kotlin
> suspend fun anotherFunction() {
>     val result = getData("data").await()
> }
> ```

I have tried this but did not work for me. Am I missing something?

```
    override suspend fun getAccessToken(): String {
        try {
            return getData().await()
        } catch (e: Exception) {
            logger.error(e) { "request failed" }

            throw e
        }
    }
    
        @Cacheable
    fun getData(): CompletableFuture<String> = CoroutineScope(Dispatchers.Default).future {
        println("fetching the data")

        return@future "test"
    }
    
```
