### ISSUE TITLE
 Cache avalanche

### ISSUE THREAD

**Issue by tmtbe** [micronaut-projects/micronaut-cache#233]
Hi，

In the case of cache failure, high-concurrency scenarios will cause cache avalanches. It is recommended to add an asynchronous cache refresh mechanism, such as Caffeine's RefreshAfterWrite, which can converge concurrent cache penetration and refresh the cache asynchronously.

Thanks

**Comment by graemerocher** [comment]
Is this an idea / feature request / bug ? Seems like it would be better to start first with a discussion https://github.com/micronaut-projects/micronaut-core/discussions

**Comment by tmtbe** [comment]
ok
