### ISSUE TITLE
Cached call to `byte[]` response fails when wrapped in `Single<HttpResponse<byte[]>>`

### ISSUE THREAD

**Issue by Guy-Incognito** [micronaut-projects/micronaut-cache#234]
Cached call to byte[] response fails when wrapped in HttpResponse<byte[]>
Calling the following endpoint twice fails on the second time with:
 io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

```    /**
     * Returns test value wrapped in HttpResponse.
     * This call will fail on refresh (i.e second call)
     *
     * @return the test value.
     */
    @Cacheable("files")
    @Get(value = PATH_FAILS, produces = "application/octet-stream")
    public HttpResponse<byte[]> getFiles() {
        return HttpResponse.ok(value);
    }
```

### Steps to Reproduce

1. Setup Micronaut 2.1.1 Project with caffeine
2. Create controller with @Cacheable annotation and returning HttpResponse<byte[]>. 
3. Call multiple times.

### Expected Behaviour

On the second call, the value should be served from cache.

### Actual Behaviour

Exception Thrown: [default-nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Error writing final response: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

### Environment Information

- **Operating System**: Linux version 5.4.67-1-MANJARO
- **Micronaut Version:** 2.1.1
- **JDK Version:** 11

### Example Application

- [Link to github repository with example that reproduces the issue](https://github.com/Guy-Incognito/micronaut-cache-bug)

Just run the tests in the example application.

**Comment by jameskleeh** [comment]
@Guy-Incognito Unfortunately we cannot support caching http responses. The response itself is mutable and the body is mutated to free the bytes after its written. Mutable responses are not designed to be written multiple times
