### ISSUE TITLE
A function in a class with @CacheConfigs gets processed even without @Cacheable or other such annotations

### ISSUE THREAD

**Issue by dave08** [micronaut-projects/micronaut-cache#257]
It seems like https://github.com/micronaut-projects/micronaut-cache/blob/80222a6ee95856c9c1fd913b1a7af5adff8a0444/cache-core/src/main/java/io/micronaut/cache/interceptor/CacheInterceptor.java#L118 checks for `CacheConfigs` stereotype, and intercepts functions not annotated at all in the whole class, which leads to bugs like functions returning `Flow` returning only one value (side-effect of https://github.com/micronaut-projects/micronaut-cache/blob/80222a6ee95856c9c1fd913b1a7af5adff8a0444/cache-core/src/main/java/io/micronaut/cache/interceptor/CacheInterceptor.java#L153). Which is wrong when not even trying to save a cache on such a function.

It should not even try to process such a function.

**Comment by alvarosanchez** [comment]
Why would you put `@CacheConfig` in class where you don't want any caching?

**Comment by dave08** [comment]
@alvarosanchez Some functions in that class have `@Cachable` and others don't. If `@CacheConfig` is included on the class, it affects all functions whether cachable or not...
