### ISSUE TITLE
Add support for using Apache Ignite

### ISSUE THREAD

**Issue by pditommaso** [micronaut-projects/micronaut-cache#26]
[Apache Ignite](https://apacheignite-mix.readme.io/docs/getting-started) is an excellent distributed cache and computing engine. It could provide a nice caching, [Hibernate L2 cache](https://apacheignite.readme.io/v1.5/docs/hibernate-l2-cache) and [web session clustering](https://ignite.apache.org/use-cases/caching/web-session-clustering.html) solution for MN applications.

**Comment by schernolyas** [comment]
Hi @pditommaso !
You are not alone with Apache Ignite! Support of Apache Ignite is moved to new repository. It is https://github.com/micronaut-projects/micronaut-ignite . I am working on the integration too :-)

**Comment by alvarosanchez** [comment]
Closing this issue since the support is being worked on a different repo.
