### ISSUE TITLE
Implementations of get(Object key, Argument<T> requiredType, Supplier<T> supplier) are broken

### ISSUE THREAD

**Issue by alparslanavci** [micronaut-projects/micronaut-cache#29]
The javadoc of  `SyncCache.get(key, requiredType, supplier)` (https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/cache/SyncCache.java#L65) says that:

> If the value is not found the specified {@link Supplier} will be invoked and the return value cached.

However, the return value is not cached on the current implementations. Please see the test below, it fails for Hazelcast, Ehcache, and Infinispan:

```
void "test get with supplier"() {
    given:
    ApplicationContext applicationContext = createApplicationContext()
    CacheManager cacheManager = applicationContext.getBean(CacheManager)

    when:
    SyncCache syncCache = applicationContext.get("test", SyncCache).orElse(cacheManager.getCache('test'))

    syncCache.get("five", Integer, new Supplier<Integer>() {
        Integer get() {
            return 5
        }
    })
    PollingConditions conditions = new PollingConditions(timeout: 15, delay: 0.5)

    then:
    conditions.eventually {
        syncCache.get("five", Integer).isPresent()
    }

    cleanup:
    applicationContext.stop()
}
```

Is this a bug, or am I missing something about the contract?

**Comment by alvarosanchez** [comment]
It's a bug, good catch

**Comment by alvarosanchez** [comment]
@alparslanavci just FYI, got the fix in the works already. Will push soon.

**Comment by alparslanavci** [comment]
Thanks for the quick fix @alvarosanchez!
