### ISSUE TITLE
Hazelcast cache implementation

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-cache#3]
related to: https://github.com/micronaut-projects/micronaut-core/projects/5#card-14137012

**Comment by niravassar** [comment]
I have created a branch for this work. I would like @jameskleeh to take a look at it and review some of the aspects with me, before I create a PR. It is a basic implementation that will work with the `@Cacheable` annotations within Micronaut.

*branch*
https://github.com/micronaut-projects/micronaut-cache/tree/hazelcast

**Comment by niravassar** [comment]
We are going to make this implementation focused around a Hazelcast client, that will connect to an existing hazelcast server with instances and nodes.
