### ISSUE TITLE
Reactive @Cacheable method wraps original exeption into CompletionException

### ISSUE THREAD

**Issue by Im-dex** [micronaut-projects/micronaut-cache#304]
### Steps to Reproduce

1. Create reactive `@Cacheable` method
2. Return an error from this method

### Expected Behaviour

The original exception should be returned

### Actual Behaviour

CompletionException, wrapping original exception, is returned

### Environment Information

- **Operating System**: Win10
- **Micronaut Version:** 2.3.4, 2.4.0
- **JDK Version:** 11, 15

### Example Application

https://github.com/Im-dex/cacheable-bug

**Comment by Im-dex** [comment]
Still actual

**Comment by graemerocher** [comment]
Seems to be fixed in master see #304
