### ISSUE TITLE
Most cache metrics remain zero

### ISSUE THREAD

**Issue by easimon** [micronaut-projects/micronaut-cache#306]
When using micronaut-cache-caffeine, and exposing metrics via prometheus, most cache metrics show 0 forever.
Micronaut 1.x shows the same behaviour, so this might be a old bug, but it's still the same with micronaut 2.4.1.

### Steps to Reproduce

1. Create application that uses a cache and exposes cache metrics (see example application)
2. Start it
3. Open http://localhost:8080/prometheus

### Expected Behaviour

The cache metrics should become > 0.0 over time.

### Actual Behaviour

Only the `cache.size` is reported != 0, everything else stays 0.0 forever. In the example application, at least `cache.gets` and `cache.puts` should report values > 0, since the cache contains a value.

I am not sure about the `cache.evictions` and `cache.eviction.weight` counters mean or should display, but these stay 0 as well, like below.

```
 HELP cache_puts_total The number of entries added to the cache
# TYPE cache_puts_total counter
cache_puts_total{cache="mycache",} 0.0
# HELP cache_eviction_weight_total The sum of weights of evicted entries. This total does not include manual invalidations.
# TYPE cache_eviction_weight_total counter
cache_eviction_weight_total{cache="mycache",} 0.0
# HELP cache_evictions_total cache evictions
# TYPE cache_evictions_total counter
cache_evictions_total{cache="mycache",} 0.0
# HELP cache_size The number of entries in this cache. This may be an approximation, depending on the type of cache.
# TYPE cache_size gauge
cache_size{cache="mycache",} 1.0
# HELP cache_gets_total the number of times cache lookup methods have returned an uncached (newly loaded) value, or null
# TYPE cache_gets_total counter
cache_gets_total{cache="mycache",result="hit",} 0.0
cache_gets_total{cache="mycache",result="miss",} 0.0
```

### Environment Information

- **Operating System**: MacOS 10.15
- **Micronaut Version:** 2.4.1
- **JDK Version:** OpenJDK 11

### Example Application

https://github.com/easimon/micronaut-experiments/tree/cache-metrics

Check out the branch `cache-metrics`, and run `./mvnw test`. There is one test failing that expects the cache counters to be non-zero.

Or build it with `./mvnw package -DskipTests`, start it, and open http://localhost:8080/prometheus

While I deactivated all other metrics for this example, activating them does not "heal" the cache metrics.

**Comment by ben-manes** [comment]
Statistics has to be enabled for Caffeine to record them, and there appears to be a flag in Micronaut. Your configuration doesn't seem to be enabling it. That's a guess as a quick glance of the integration.

https://github.com/micronaut-projects/micronaut-cache/blob/67d0c94596c5f500f5be8748b88c63bde9602448/cache-caffeine/src/main/java/io/micronaut/cache/caffeine/DefaultSyncCache.java#L202-L204

**Comment by easimon** [comment]
That was too easy, the setting solved it -- at least almost. With this setting (`caches.mycache.record-stats: true`) , the metrics increase (so the previously failing test is now green), except the `cache.puts` counter, which remains 0.

**Comment by ben-manes** [comment]
hmm, caffeine doesn’t instrument puts (we strongly advise loads  instead). Maybe micronaut doesn’t instrument it separately.

**Comment by ben-manes** [comment]
Oh, this is micrometer metrics. That is known to have a wrong mapping and uses `loadCount`, copy-pasted from the Guava metrics which had this mistake. See https://github.com/micrometer-metrics/micrometer/issues/2215

**Comment by easimon** [comment]
Thanks for explaining this! Since this seems a different issue than my initial "no metrics at all" problem, I think it would be fine to close this issue, since it was a misconfiguration issue on my side.

The `cache.puts` being there, but zero, is something else, and I think deserve a more specific issue.

**Comment by easimon** [comment]
TDLR for others falling for this: 

If you need stats from caffeine, they need to be activated in config, similar to the following:

```
  caches:
    mycache:
      record-stats: true
```
