### ISSUE TITLE
@Cacheable Publisher returns wrong results when multiple elements emitted

### ISSUE THREAD

**Issue by sulume** [micronaut-projects/micronaut-cache#336]
`@Cacheable` seems to cache only one element for `Publisher`s by taking `firstElement()` below.  This changes the observable behavior of the annotated method, which is surprising.
https://github.com/micronaut-projects/micronaut-cache/blob/27436c4c26af755a119c4389a7ffe3f70cc89608/cache-core/src/main/java/io/micronaut/cache/interceptor/CacheInterceptor.java#L154

[The document](https://micronaut-projects.github.io/micronaut-cache/snapshot/guide/#cache-abstraction) just says "the emitted result will be cached" and does not elaborate its support or limitations for non-blocking types much.  It might cover single-emitting ones only but the type is generic for multiple.  It may not be reasonable to cache many or unbounded elements as one, but still useful for several.  I don't really think the expected behavior is obvious.

I think there are ways to address this issue, for example,

a) cache as a whole, as long as the runtime resource allows
b) report a runtime error for the unsupported use of `@Cacheable` for multi-emitting `Producer`s
c) cache one or several and fallback to invoke the original when desired more

a) or b) would work at a minimum although it's nice if the behavior is customizable.  a) may be most intuitive and can be utilized at users' own risk whereas b) is just a foolproof on the limitation.  c) is just a possible way to benefit even for unbounded cases but may not be natural.

And besides, I'd like the behavior to be documented in detail.

### Steps to Reproduce

1. configure a cache with Caffeine
2. write a method to return `Publisher` emitting some number of elements
3. test calling it w/ and w/o `@Cacheable`

### Expected Behaviour

The same sequence of elements should be emitted by the returned Publisher whether cached.

### Actual Behaviour

The cached result ends up with the first element only. (The result matches only when exactly one element emitted.)

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 2.5.5
- **JDK Version:** 11.0.9.1

**Comment by graemerocher** [comment]
I agree this behaviour should either be documented or fixed

**Comment by graemerocher** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-cache/pull/337/files#diff-ab75f73a14c7c3a93fd5e8a033bc47ab2cfb6cb53e484602433da98026826488R132
