### ISSUE TITLE
Specify Hazelcast config files in application.yml  

### ISSUE THREAD

**Issue by JJRdec** [micronaut-projects/micronaut-cache#396]
### Feature description

I want to be able to easily specify which Hazelcast xml config file is to be used through a properties file. This would be useful for me to have easily switch between Hazelcast configurations for different environments (dev, test, prod).

Spring boot offers this and can be configured within a application.properties file as such.
```
spring.hazelcast.config=hazelcast-dev.xml
```

Maybe similar functionality already exists. However, I could not find this documented anywhere.

Many thanks in advance.

**Comment by sdelamo** [comment]
@Richardson-e  please work on this
