### ISSUE TITLE
Cache Key serialization fails for LocalDateTime parameter type

### ISSUE THREAD

**Issue by jacekgajek** [micronaut-projects/micronaut-cache#404]
### Expected Behavior

Given (kotlin)
```
    @Cacheable
    suspend fun foo(t: LocalDateTime): Foo {
        return Foo(t)
    }
```
foo should be properly cached with a LocalDateTime parameter

### Actual Behaviour

Code location: `io.micronaut.runtime.converters.time.TimeConverterRegistrar::resolveFormatter`

1. Key serialization fails because the default formatter is `DateTimeFormatter.RFC_1123_DATE_TIME` which throws exception if a chronodate doesn't support an OffsetSecond field.
2. The `resolveFormatter` seems to look for a `Format` annotation, but adding it to a method or a parameter didn't work. In fact, when debugging I've discovered that `context.getAnnotationMetada()` returns `EmptyAnnotationMetadata`. Maybe incorrect `context` is passed?

So these are two separate problems:
1. Don't use `RFC_1123_DATE_TIME` for unsupported chronos
2. Fix `resolveFormatter` so it takes `@Format` annotation on a cacheable method's parameter.

### Steps To Reproduce

micronautVersion=3.3.0
with redis cache dependency added and configured:
```
redis:
  uri: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
  caches:
    foo:
  cache:
    charset: UTF-8
    expire-after-write: 1h
```

Create a controller

```
data class Foo(val t: LocalDateTime, val created:  LocalDateTime = LocalDateTime.now())
@Controller
@CacheConfig("foo")
class FooController() {

    @Get(uri = "/api/foo")
    @Cacheable
    suspend fun foo(t: LocalDateTime): Foo {
        return Foo(t)
    }
}
```
call the `/api/foo?t=2022-02-03T12:00:00` endpoint.

### Environment Information

- Ubuntu 20
- JVM Azul 17

### Version

3.3.0

**Comment by jfsanchez91** [comment]
Here is a test case that validates to issue:
```groovy
package io.micronaut.cache.serialize

import io.micronaut.core.convert.ConversionService
import spock.lang.Specification

import java.nio.charset.Charset
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.OffsetDateTime
import java.time.OffsetTime
import java.time.ZoneId
import java.time.ZoneOffset
import java.time.ZonedDateTime

class DefaultStringKeySerializerSpec extends Specification {
    void "test TemporalAccessor serialization"() {
        given:
        final var serializer = new DefaultStringKeySerializer("cacheName", Charset.defaultCharset(), ConversionService.SHARED)

        expect:
        new String(serializer.serialize(sourceObject).get(), Charset.defaultCharset()) == "cacheName:$result"

        where:
        sourceObject | result
        LocalDate.of(2022, 8, 12)                                               | "2022-08-12"
        LocalDateTime.of(2022, 8, 12, 12, 19)                                   | "2022-08-12T12:19:00"
        OffsetTime.of(12, 19, 0, 0, ZoneOffset.ofHours(5))                      | "12:19:00+05:00"
        OffsetDateTime.of(2022, 8, 12, 12, 19, 0, 0, ZoneOffset.ofHours(5))     | "2022-08-12T12:19:00+05:00"
        ZonedDateTime.of(2022, 8, 12, 12, 19, 0, 0, ZoneOffset.ofHours(5))      | "2022-08-12T12:19:00+05:00"
        ZonedDateTime.of(2022, 8, 12, 12, 19, 0, 0, ZoneId.of("Europe/Berlin")) | "2022-08-12T12:19:00+02:00[Europe/Berlin]"
        LocalDateTime.of(2022, 8, 12, 12, 19).toInstant(ZoneOffset.UTC)         | "2022-08-12T12:19:00Z"
    }
}
```

**Comment by wetted** [comment]
I have an example project at https://github.com/wetted/cache404 to test the fix implemented on https://github.com/micronaut-projects/micronaut-core/pull/8963. However, that PR needs to be updated by @jfsanchez91 to merge latest changes from core.
