### ISSUE TITLE
Latest micronaut-cache-tck doesn't get published do Maven Central

### ISSUE THREAD

**Issue by vasac** [micronaut-projects/micronaut-cache#408]
### Issue description

Latest version of `micronaut-cache-tck` available at Maven Central is `3.0.0` while it should be `3.1.0`. All other artifacts from `io.micronaut.cache` group are available in version `3.1.0` - https://search.maven.org/search?q=g:io.micronaut.cache

**Comment by burtbeckwith** [comment]
Thanks for reporting this. It's available in v3.1.1: https://repo1.maven.org/maven2/io/micronaut/cache/micronaut-cache-tck/3.1.1/

Note that it won't be updated in the Micronaut BOM until 3.3.2, so you need to manually specify the version until then
