### ISSUE TITLE
Update to major versions of Cache integrations

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-cache#496]
### Issue description

e.g. Hazelcast upgrade

**Comment by timyates** [comment]
There's a PR here to update `caffeine`, `hazelcast` and `infinispan` https://github.com/micronaut-projects/micronaut-cache/pull/513

EhCache isn't playing nicely, so will be done later

@alvarosanchez Do you have knowledge of ehcache?  Asking as your name is all over the code 🤞 😄

**Comment by alvarosanchez** [comment]
Yeah I wrote the initial integration... with ehcache 3.8 😅

**Comment by sdelamo** [comment]
@timyates can we close this?

**Comment by wetted** [comment]
> @timyates can we close this?

@sdelamo There is a PR #531 for this. I have merged all the changes from master into it, but there is a still an ehcache test failing around the terracotta testcontainer. I spent some time trying to get it to work. I'll check with  Tim when he's back and maybe we can get it working.

**Comment by wetted** [comment]
#601 updates Caffeine to latest
