### ISSUE TITLE
How to use @Cacheable parameters attribute ?

### ISSUE THREAD

**Issue by hrpath** [micronaut-projects/micronaut-cache#71]
Hi 

I'm trying to cache a same type return but with different implementation

```groovy
 @Cacheable(keyGenerator = GeneratedMessageV3KeyGenerator)
    CountryOuterClass.Country findCountryByCode(String code) {
        countryService.find(ReferenceCriteria.ReferenceGetCriteria.newBuilder().setCode(code).build())
    }
```

Here I want the key to be composed like `'country-$code'`

I did not find document on how to pass the `country` prefix using keyGenerator interface or even how to user the `parameters` attributes in the annotation.

Is there some examples to display some way to achieve this ?

-----

Edit this is working but is this the best practice ?
I pass and extra parameters which is kinda error prone compared to an annotation parameter.

```groovy
 @Cacheable(keyGenerator = GeneratedMessageV3KeyGenerator)
    CountryOuterClass.Country findCountryByCode(String code, String prefix = 'country') {
        countryService.find(ReferenceCriteria.ReferenceGetCriteria.newBuilder().setCode(code).build())
    }
```

Thanks you, we really enjoy working with micronaut suite

**Comment by alvarosanchez** [comment]
Without seeing the `GeneratedMessageV3KeyGenerator` implementation is hard to tell, but likely you are doing it wrong.

It should be something like:

```groovy
@Introspected
class GeneratedMessageV3KeyGenerator implements CacheKeyGenerator {

    @Override
    Object generateKey(AnnotationMetadata annotationMetadata, Object... params) {
        return "country-" + params[0]
    }

}
```

**Comment by Solido** [comment]
Thanks this was my implementation, my questions was related to parameters which is not documented and how it can be used.
