### ISSUE TITLE
Document how to disable Hazelcast

### ISSUE THREAD

**Issue by vnesek** [micronaut-projects/micronaut-cache#75]
When including io.micronaut.cache:micronaut-cache-hazelcast into build,
hazelcast will be always initialized, either as client or as standalone instance.

Please add property hazelcast.enabled to have option of disabling hazelcast autoconfiguration.

**Comment by alvarosanchez** [comment]
It's already supported: https://github.com/micronaut-projects/micronaut-cache/blob/master/cache-hazelcast/src/main/java/io/micronaut/cache/hazelcast/package-info.java#L22

However, it should be better documented. Would you be willing to put together a PR mentioning it?
Thanks!

**Comment by abracadv8** [comment]
I can add this to the doc.  Is there any corporate CLA that needs to be filled out beforehand?

**Comment by ilopmar** [comment]
@abracadv8 Thanks. Once you submit the PR you will need to sign the CLA.

**Comment by abracadv8** [comment]
No problem.  @ilopmar  - Do you have a copy of the CLA that I can provide our legal team for reference?

**Comment by ilopmar** [comment]
@abracadv8 sure: https://cla-assistant.io/micronaut-projects/micronaut-cache
