### ISSUE TITLE
Cache metrics missing

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-cache#94]
With the default configuration i get some cache metrics from micrometer. The cache_size metric seems to be sent (and reports activity) but cache_gets and cache_puts is not sent.

**Comment by alvarosanchez** [comment]
Which cache provider are you using? Caffeine (the default)?

Micronaut version?

**Comment by ckosmowski** [comment]
Yes, Caffeine. And micronaut 1.3.0.

**Comment by ckosmowski** [comment]
Please reopen, this is still a Problem for us

**Comment by graemerocher** [comment]
Implemented by https://github.com/micronaut-projects/micronaut-cache/pull/112

**Comment by ckosmowski** [comment]
The problem persists with 2.2.0. We have cache-size metrics as expected. Cashes seem to work properly but still cache_gets, cache_puts, cache_evictions are always 0.

**Comment by ckosmowski** [comment]
This still persists with Version 3.1.0 we set record-stats everywhere but still we only get cache-size metrics. No information about puts / gets etc.

**Comment by alvarosanchez** [comment]
Can you upload a sample application that reproduces the issue?

**Comment by ckosmowski** [comment]
#112 seemed to fix it for us. We got the cache-metrics for services using micronaut 2.2.X. For the new services 2.3.X it's broken again.

I don't know how to supply a sample to reproduce the issue since it has to involve a meter registry like influxDB and something to monitor it?
